---
- name: Resize directory
  hosts: all
  tasks:
   - name: Check if /dev/rl exists
    shell: "[ -d /dev/rl ]"
    register: rl_exists

   - name: Perform actions if /dev/rl exists
     debug:
      msg: "RL path exists!"
     when: rl_exists.rc == 0

  - name: Perform actions if /dev/rl does not exist
    debug:
     msg: "RL path does not exist."
    when: rl_exists.rc != 0
