---
- name: Resize directory
  hosts: all
  tasks:
    - name: Check if /dev/rl exists
      set_fact:
        avaibleRLPath: true
      when: test -d /dev/rl  # Use the test command directly in when clause

    - name: Perform actions if /dev/rl exists
      block:
        - debug: msg="RL path exists!"  # Example action
        # Add other tasks for rl_exists here
      when: avaibleRLPath

    - name: Perform actions if /dev/rl does not exist
      block:
        - debug: msg="RL path does not exist."  # Example action
        # Add other tasks for rl_doesnotexists here
      when: not avaibleRLPath
