---
- name: Resize directory
  hosts: all
  tasks:
   - name: Check if /dev/rl exists
     stat:
       path: /dev/rl
     register: rl_stat    
   - name: Perform actions if /dev/rl exists
     debug:
       msg: "RL path exists!"
     when: rl_stat.stat.isdir

   - name: Perform actions if /dev/rl does not exist
     block:
     - debug:
        msg: "RL path does not exist."
     when: not rl_stat.stat.exists
