---
- name: Resize directory
  hosts: all
  tasks:
    - name: Check for available RL paths
      block:
      - name: Set RL_PATH to /dev/rl if it exists
        set_fact:
          rl_path: "/dev/rl"
        when:
          - test -d "/dev/rl"

      - name: Set RL_PATH to /dev/rl_microservices if it exists
        set_fact:
          rl_path: "/dev/rl_microservices"
        when:
          - test -d "/dev/rl_microservices"

      - name: Set RL_PATH to /dev/rocky if it exists
        set_fact:
          rl_path: "/dev/rocky"
        when:
          - test -d "/dev/rocky"

      - name: Fail if no RL path found
        fail:
          msg: "RL path not found"
        when: rl_path == ''

    - name: Extend logical volume
      command: "lvextend -L {{ fs_size }} {{ rl_path }}"
      when: rl_path != ''  # Only execute if RL_PATH is set

    - name: Grow XFS filesystem
      command: "xfs_growfs {{ rl_path }}"
      when: rl_path != ''  # Only execute if RL_PATH is set
